<Project>
    <PropertyGroup>
        <AssemblyVersion>1.0.0</AssemblyVersion>
    </PropertyGroup>
    <PropertyGroup Label="Paths">
        <EnableDefaultItems>false</EnableDefaultItems>
        <BaseOutputPath>bin</BaseOutputPath>
        <BaseIntermediateOutputPath>obj</BaseIntermediateOutputPath>
    </PropertyGroup>
</Project>