<Project Sdk="Microsoft.NET.Sdk">
    <Target Name="PlatformCheck" BeforeTargets="_CheckForInvalidConfigurationAndPlatform">
        <Error Text="Unsupported platform '$(Platform)'" Condition="'$(Platform)' != 'x64' and '$(Platform)' != 'ARM64'"/>
    </Target>

    <PropertyGroup>
        <Authors>Jan Kos</Authors>
        <Description>Modern low-level bindings for the GLFW library</Description>
        <Copyright>Copyright 2025 (c) Jan Kos. All rights reserved.</Copyright>
        <ProjectUrl>https://github.com/isojk/csglfw</ProjectUrl>
        <RepositoryUrl>https://github.com/isojk/csglfw</RepositoryUrl>

        <AssemblyName>Isojk.Csglfw</AssemblyName>
        <AssemblyVersion>0.0.2</AssemblyVersion>
        <FileVersion>0.0.2.0</FileVersion>
        <OutputType>Library</OutputType>
        <TargetFrameworks>net9.0;net9.0-windows;net9.0-macos;net8.0;net8.0-windows;net8.0-macos</TargetFrameworks>
        <Platforms>x64;ARM64</Platforms>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <DisableCalli>false</DisableCalli>
        <GeneratedCodeFolder>$(MSBuildThisFileDirectory).generated</GeneratedCodeFolder>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Isojk.Csglfw</RootNamespace>

        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
        <GenerateTargetFrameworkAttribute>true</GenerateTargetFrameworkAttribute>
        <IsAotCompatible>true</IsAotCompatible>
        <NoWarn>NU5100</NoWarn>
        <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DebugType>Embedded</DebugType>
        <EmbedAllSources>True</EmbedAllSources>
        <Optimize>false</Optimize>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>None</DebugType>
        <DebugSymbols>false</DebugSymbols>
        <Optimize>true</Optimize>
    </PropertyGroup> 

    <PropertyGroup Label="Package Info">
        <PackageId>Isojk.Csglfw</PackageId>
        <PackageVersion>$(AssemblyVersion)-$(Platform)</PackageVersion>
        <PackageTags>glfw gui window graphics gl opengl</PackageTags>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    </PropertyGroup>

    <Target Name="_GLFW3PrintProperties" BeforeTargets="BeforeBuild">
        <Message Importance="High" Text="Configuration: $(Configuration)" />
        <Message Importance="High" Text="Platform: $(Platform)" />
    </Target>

    <ItemGroup Label="Source Files">
        <Compile Include="src/API.Tokens.cs" />
        <Compile Include="src/API.Types.cs" />
		<Compile Include="src/API.Functions.cs" />
        <Compile Include="src/API.Functions.Unsafe.cs" />
        <Compile Include="src/API.Loader.cs" />
        <Compile Include="src/Helpers.cs" />
        <Compile Include="src/Diagnostics.cs" />
    </ItemGroup>
        
    <ItemGroup>
        <!-- Native dynamic libraries -->
        
        <!-- osx-arm64 -->
        <_GLFW3_DynamicLibraryFile Include="$(MSBuildThisFileDirectory)runtimes\osx-arm64\native\libglfw.3.dylib">
            <TargetRid>osx-arm64</TargetRid>
        </_GLFW3_DynamicLibraryFile>

        <!-- osx-x64 -->
        <_GLFW3_DynamicLibraryFile Include="$(MSBuildThisFileDirectory)runtimes\osx-x64\native\libglfw.3.dylib">
            <TargetRid>osx-x64</TargetRid>
        </_GLFW3_DynamicLibraryFile>

        <!-- win-x64 -->
        <_GLFW3_DynamicLibraryFile Include="$(MSBuildThisFileDirectory)runtimes\win-x64\native\glfw3.dll">
            <TargetRid>win-x64</TargetRid>
        </_GLFW3_DynamicLibraryFile>

        <!-- Native static libraries -->

        <!-- osx-arm64 -->
        <_GLFW3_StatibLibraryFile Include="$(MSBuildThisFileDirectory)staticLibraries\osx-arm64\native\libglfw3.a">
            <TargetRid>osx-arm64</TargetRid>
        </_GLFW3_StatibLibraryFile>

        <!-- osx-x64 -->
        <_GLFW3_StatibLibraryFile Include="$(MSBuildThisFileDirectory)staticLibraries\osx-x64\native\libglfw3.a">
            <TargetRid>osx-x64</TargetRid>
        </_GLFW3_StatibLibraryFile>

        <!-- win-x64 -->
        <_GLFW3_StatibLibraryFile Include="$(MSBuildThisFileDirectory)staticLibraries\win-x64\native\glfw3.lib">
            <TargetRid>win-x64</TargetRid>
        </_GLFW3_StatibLibraryFile>

        <!-- win-x64 -->
        <_GLFW3_StatibLibraryFile Include="$(MSBuildThisFileDirectory)staticLibraries\win-x64\native\glfw3_mt.lib">
            <TargetRid>win-x64</TargetRid>
        </_GLFW3_StatibLibraryFile>

        <!-- Packaging -->
        <None Include="README.md">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
        </None>

        <None Include="LICENSE">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
        </None>

        <None Include="ACKNOWLEDGEMENTS">
            <Pack>true</Pack>
            <PackagePath>\</PackagePath>
        </None>

        <None Include="buildTransitive\**">
            <Pack>true</Pack>
            <PackagePath>buildTransitive</PackagePath>
        </None>

        <None Include="@(_GLFW3_DynamicLibraryFile)">
            <Visible>False</Visible>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <PackageCopyToOutput>true</PackageCopyToOutput>
            <Pack>true</Pack>
            <PackagePath>runtimes\%(TargetRid)\native\%(Filename)%(Extension)</PackagePath>
        </None>

        <None Include="@(_GLFW3_StatibLibraryFile)" Condition="'$(GLFWEnableStaticBuild)' != 'true'">
            <Visible>False</Visible>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <PackageCopyToOutput>false</PackageCopyToOutput>
            <Pack>true</Pack>
            <PackagePath>staticLibraries\%(TargetRid)\native\%(Filename)%(Extension)</PackagePath>
        </None>
    </ItemGroup>
</Project>