<Project>
    <PropertyGroup>
        <_GLFWIsWindows>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows)))</_GLFWIsWindows>
        <_GLFWIsOSX>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))</_GLFWIsOSX>
        <_GLFWIsLinux>$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))</_GLFWIsLinux>
        <_GLFWIsInRestore>false</_GLFWIsInRestore>
    </PropertyGroup>
    <PropertyGroup Condition="$(_GLFWIsWindows)">
        <_GLFWDynamicLibraryName>glfw3.dll</_GLFWDynamicLibraryName>
        <_GLFWStaticLibraryName>glfw3_mt.lib</_GLFWStaticLibraryName>
    </PropertyGroup>
    <PropertyGroup Condition="$(_GLFWIsOSX)">
        <_GLFWDynamicLibraryName>libglfw.3.dylib</_GLFWDynamicLibraryName>
        <_GLFWStaticLibraryName>libglfw3.a</_GLFWStaticLibraryName>
    </PropertyGroup>
    <PropertyGroup Condition="$(_GLFWIsLinux)">
        <_GLFWDynamicLibraryName>libglfw.so.3.4</_GLFWDynamicLibraryName>
        <_GLFWStaticLibraryName>libglfw3.a</_GLFWStaticLibraryName>
    </PropertyGroup>
</Project>
